### ISSUE TITLE
Moodlight color state after reboot / powercycle

### ISSUE THREAD

**Issue by nagyrobi** [HASwitchPlate/openHASP#123]
**Is your feature request related to a problem? Please describe.**
Similar to [group items](https://github.com/HASwitchPlate/openHASP/issues/99), moodlight color, state (and [brightness](https://github.com/HASwitchPlate/openHASP/issues/59#issuecomment-787106735) after implemented) should be remembered after reboot / powercycle.
If HA and plate both reboot _while the moodlight was turned off_, nobody remembers what was the pre-selected moodlight attribute. At HA reboot, the current of moodlight color is read from the plate because HA [doesn't keep the color attribute](https://github.com/home-assistant/core/issues/2316) when light is off. If plate also reboots during this time (eg. power outage affecting all devices), nobody remembers what was the pre-selected color.

**Describe the solution you'd like**
When `moodlight` command comes in with `color` key, check if moodlight color info is saved to the flash. If moodlight color info in flash is different of what came with the command, write to flash the new color info (save flash writes if every `{"state":"true"}` command comes with the same color info every time...)
At boot restore moodlight color info (and state) from flash.

**Describe alternatives you've considered**
Only this

**Additional context**
Not applicable

**Comment by fvanroie** [comment]
Moved to #99 .
