### ISSUE TITLE
Feature request: Popup object for events

### ISSUE THREAD

**Issue by MatijaTerzic** [HASwitchPlate/openHASP#136]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
For example when in Home Assistant a state changes from on / off (eg. lights) a popup is show with custom text and after x ms goes away.

**Describe alternatives you've considered**
NA

**Additional context**
NA

**Comment by nagyrobi** [comment]
Also with [page attributes](https://haswitchplate.github.io/openHASP-docs/#pages/#page-attributes) should be possible to create "hidden" pages which don't ever appear during normal page navigation, but can be shown by MQTT commands - thus achieving a behavior of pop-up screens.

**Comment by fvanroie** [comment]
@MatijaTerzic Does this sufficiently answer your question?

**Comment by MatijaTerzic** [comment]
@fvanroie yes thank you

**Comment by MatijaTerzic** [comment]
Ok
