### ISSUE TITLE
Feature request: GPIO info on request

### ISSUE THREAD

**Issue by nagyrobi** [HASwitchPlate/openHASP#145]
**Is your feature request related to a problem? Please describe.**
To verify the status of the GPIO settings from HA side. At boot HA could check the plate's gpio settings and if finds them inappropriate, push down the right config.

**Describe the solution you'd like**
When publishing an empty payload to `hasp/plate/config/gpio` it would be nice if the plate would respond with current GPIO settings in effect (if no GPIO setting present, respond `none` or something easily detectable from an error). Optionally put it in `state/statusupdate`.

**Describe alternatives you've considered**
n/a

**Additional context**
n/a

**Comment by nagyrobi** [comment]
Edit: on Lanbon L8 pushing `{"config":[2360346,2491680,2623009,2097420,2097678,2097947,0,0]}` to `hasp/<nodename>/config/gpio` doesn't work on 0.5.0.

**Comment by fvanroie** [comment]
> Edit: on Lanbon L8 pushing {"config":[2360346,2491680,2623009,2097420,2097678,2097947,0,0]} to hasp/<nodename>/config/gpio doesn't work on 0.5.0.

See #146
