### ISSUE TITLE
Color picker rectangular not possible

### ISSUE THREAD

**Issue by nagyrobi** [HASwitchPlate/openHASP#147]
### Perform all steps below and tick them with [x]
- [x] Check the related part of the [Documentation](https://haswitchplate.github.io/openHASP-docs/)
- [x] Update openHASP to the latest version
- [x] Reproduce the issue and describe all steps

### Describe the bug
Trying to generate a rectancular color picker, circular appears

### To Reproduce
```json
{"page":3,"id":4,"obj":"cpicker","x":30,"y":90,"w":180,"h":180,"rect":"true"}
{"page":3,"id":4,"obj":"cpicker","x":30,"y":90,"w":180,"h":180,"rect":1}
```
results in a circular cpicker

### Expected behavior
should be rectangular

### Screenshots or video
n/a

**Comment by arovak** [comment]
Your width and height a identical resulting in a circular color picker object.
`{"page":3,"id":4,"obj":"cpicker","x":30,"y":90,"w":180,"h":80}`
will give a rectangular color picker.
Attribute 'rect' is not needed, when the object is longer then it is high a rectangular color picker is created..

**Comment by fvanroie** [comment]
The `rect` property is not used anymore, it can be removed from the docs.

There are also indications that the rectangular mode will be gone in lvgl v8.

**Comment by nagyrobi** [comment]
> There are also indications that the rectangular mode will be gone in lvgl v8.

That's sad.
Doc updated.
