### ISSUE TITLE
mqttServer array is too short 

### ISSUE THREAD

**Issue by AndreTeixeira1998** [HASwitchPlate/openHASP#150]
The definition of the array  "char mqttServer[16]" is too short for using dynamic DNS urls.

I recommend using a larger number.

Thank you

Error:
src/mqtt/hasp_mqtt_pubsubclient.cpp:57:19: error: initializer-string for array of chars is too long [-fpermissive]
 #define MQTT_HOST "homeswhome.dyndns.org";
                   ^
src/mqtt/hasp_mqtt_pubsubclient.cpp:84:25: note: in expansion of macro 'MQTT_HOST'
 char mqttServer[16]   = MQTT_HOST;

**Comment by fvanroie** [comment]
This issue is fixed in the latest [master build](https://github.com/HASwitchPlate/openHASP/actions). Feel free to test it.
