### ISSUE TITLE
Portuguese language file

### ISSUE THREAD

**Issue by AndreTeixeira1998** [HASwitchPlate/openHASP#161]
Greetings, just created the pt_PT.h header file for  src/lang/ with the definitions translated to Portuguese.
Would be grateful if you could add it to the repo.

[pt_PT.TXT](https://github.com/HASwitchPlate/openHASP/files/6460251/pt_PT.TXT)

**Comment by dgomes** [comment]
Hello André,

The proper way is to open a Pull Request

Also run a spellchecker 😉
