### ISSUE TITLE
Feature request: Button matrix uncheck all

### ISSUE THREAD

**Issue by nagyrobi** [HASwitchPlate/openHASP#183]
**Is your feature request related to a problem? Please describe.**
A button matrix with `"toggle":1` and `"one_check":1` will start with all buttons unchecked (not pressed). In the example below the button matrix implements a radio station preset selector.
![kép](https://user-images.githubusercontent.com/1550668/124308207-3b6d4d00-db69-11eb-9d86-16d3b376eb35.png)
After pressing a button (`val = 2`), there's no way to release it without having to press another button:
![kép](https://user-images.githubusercontent.com/1550668/124308378-7ec7bb80-db69-11eb-9e06-0e07b7f32580.png)
The use case is that the button should be in pressed state while that radio preset is playing. If the player is stopped (or it's playing something else than the button presets), no radio is playing, thus all buttons should be in released state.

**Describe the solution you'd like**
When setting val to `-1` or some magic string, all the buttons should go unselected.
Or shift the values to start with 1 for the first button, and then 0 could mean no buttons selected.

**Describe alternatives you've considered**
N/A

**Additional context**
Could be useful for dropdown too. Usually a dropdown starts with the first item in the list, but it would be useful to also be able to set an "empty" item in the dropdown, based on the logic above.

**Comment by nagyrobi** [comment]
Related discussion: https://github.com/HASwitchPlate/openHASP/discussions/180

**Comment by fvanroie** [comment]
It always comes down to what is supported by [the lvgl object](https://docs.lvgl.io/7.11/widgets/btnmatrix.html).

`one_check` only makes sure that there is _maximum_ 1 button checked... the user can't uncheck the same button once checked.
So either custom object behavior is needed or special treatment of existing properties...

Like add a `no_check` option for *pressing the same button by the user again will uncheck it again*?
Or only allow it to be reset programmatically?

**Comment by nagyrobi** [comment]
Programatically is enough for my use case.

**Comment by fvanroie** [comment]
You can try commit a5b783a, untested but should work...

**Comment by nagyrobi** [comment]
Thank you, works perfectly!
