### ISSUE TITLE
Add Captive Portal

### ISSUE THREAD

**Issue by AndreTeixeira1998** [HASwitchPlate/openHASP#196]
Problem:

Right now to configure the wifi on a Lanbon device with the OpenHASP firmware I connect to the softAP and need to constantly go to the webserver IP Address (192.168.4.1), which can be pretty tedious. I think the wifi config is pretty lacking.

Sugestion:
It would be nice to add a Captive Portal. A captive portal automatically redirects the user to a webpage when he connects the softAP. 

As an example, Tasmota does it pretty nicely and also searches for available networks.

![wificonfig](https://user-images.githubusercontent.com/47570249/128531893-a92ece54-7786-4d96-9fa7-e3c423c37600.jpg)

**Comment by fvanroie** [comment]
The PR has now been merged into the master branch. I've tested it and it just works! Thanks @AndreTeixeira1998 
I added a `HASP_USE_CAPTIVE_PORTAL` switch which defaults to `1` on the ESP32.
