### ISSUE TITLE
MQTT Port Settings not working

### ISSUE THREAD

**Issue by Qargh** [HASwitchPlate/openHASP#209]
Hi,
I changed the MQTT Port from default 1883 to 1882 via the HTTP settings dialog. These changes don't take effect after reboot. I'm not a C programmer, but at a first look I think the corresponding variable should be used in the [mqttStart()](https://github.com/HASwitchPlate/openHASP/blob/f03d231792a1646d4719c05bb1e1958b899cd583/src/mqtt/hasp_mqtt_pubsubclient.cpp#L227)-function.

openHASP version: 0.6.1
device: lanbon l8

Best regards

**Comment by fvanroie** [comment]
Good catch! This is updated for 0.6.2 and can be tested soon by using the last build in the Actions tab.
