### ISSUE TITLE
Add LovyanGFX display driver

### ISSUE THREAD

**Issue by fvanroie** [HASwitchPlate/openHASP#220]
**Is your feature request related to a problem? Please describe.**

As the list of supported devices and configurations grows, the number of firmware files to be build goes up.
TFT_eSPI uses a configuration file that is evaluated at compile time, so all hardware info is baked into the firmware binary.

**Describe the solution you'd like**

To consolidate the number of hardcoded pins/drivers in openHASP, LovyanGFX can be added as a display driver option.
It allows us to configure the bus, display- and touch-panel at runtime. [LovyanGFX](https://github.com/lovyan03/LovyanGFX) is in active development and based on TFT_eSPI.

Besides the flexible configuration parameters, LovyanGFX is touted to be *slightly* faster and supports [extra display chips](https://github.com/lovyan03/LovyanGFX/tree/master/src/lgfx/v1/panel).
LovyanGFX uses the same license as TFT_eSPI (FreeBSD License) with parts by Adafruit_GFX (BSD License).

**Describe alternatives you've considered**

Another option is [Arduino_GFX](https://github.com/moononournation/Arduino_GFX) but that is a faily recent project based on *"Adafruit_GFX, LovyanGFX, TFT_eSPI, Ucglib, and more..."*
There is no license file as of yet, so it is unclear if it will be compatible with openHASP.

**Additional context**

Speed comparison between ST7796/ILI9488 and TFT_eSPI/LovyanGFX:
https://www.youtube.com/watch?v=kRTFc2vY5A8

**Comment by fvanroie** [comment]
FT6xx6 touch driver is working too.

**Comment by fvanroie** [comment]
@paultbarrett @FamilieKlein I'm trying to get a working LovyanGFX config for the WT86-32-3ZW1.
It would be great if you could share your experience or configuration for this device. Thanks!

https://www.giters.com/Bodmer/TFT_eSPI/issues/1348 (It seems the comments on the TFT_eSPI repo were deleted... 😞)

**Comment by nagyrobi** [comment]
@fvanroie https://github.com/HASwitchPlate/openHASP/commit/8f88a6ab4818c167cf6acdec7e6e148067cf68cc

**Comment by fvanroie** [comment]
I am aware of that repository and exchanged messages with the author. The result is that we have a working TFT driver for the WT86-32-3ZW1. No touch yet...

**Comment by fvanroie** [comment]
The WT86-32-3ZW1 now is included in the dev-test builds from the Actions tab.
