### ISSUE TITLE
I have a question about the file editor

### ISSUE THREAD

**Issue by AlbertDijksma** [HASwitchPlate/openHASP#247]
Hi, I have a question about the file editor.
I am missing a save button to save the changes.
Is this correct?
My setup:
Lolin TFT 2.4" Touch Shield
Lilygo Ttgo T7 V1.5 Mini32 ESP32-WROVER-B Psram
Software version master from 6-11-2021

**Comment by nagyrobi** [comment]
Ctrl+S
