### ISSUE TITLE
ft2build.h: No such file or directory

### ISSUE THREAD

**Issue by DSRocker** [HASwitchPlate/openHASP#264]
In file included from src/hasp/hasp.cpp:34:
lib/lv_lib_freetype/lv_freetype.h:17:10: fatal error: ft2build.h: No such file or directory

******************************************************************
* Looking for ft2build.h dependency? Check our library registry!
*
* CLI  > platformio lib search "header:ft2build.h"
* Web  > https://platformio.org/lib/search?query=header:ft2build.h
*
******************************************************************

 #include "ft2build.h"
          ^~~~~~~~~~~~
compilation terminated.
*** [.pio\build\d1-mini-esp32_ili9341\src\hasp\hasp.cpp.o] Error 1
In file included from src/hasp/hasp_font.cpp:4:
lib/lv_lib_freetype/lv_freetype.h:17:10: fatal error: ft2build.h: No such file or directory

******************************************************************
* Looking for ft2build.h dependency? Check our library registry!
*
* CLI  > platformio lib search "header:ft2build.h"
* Web  > https://platformio.org/lib/search?query=header:ft2build.h
*
******************************************************************

 #include "ft2build.h"
          ^~~~~~~~~~~~
compilation terminated.
*** [.pio\build\d1-mini-esp32_ili9341\src\hasp\hasp_font.cpp.o] Error 1
=============================================================================== [FAILED] Took 50.96 seconds ===

**Comment by fvanroie** [comment]
Please make sure you include `--recursive` when [cloning the repository](https://haswitchplate.github.io/openHASP-docs/0.6.2/compiling/local/#clone-openhasp). lv_lib_freetype is a sub-module and it seems it didn't got initialized properly.

**Comment by DSRocker** [comment]
Sorry, in which file?
I tried again and cloned 0.6.2. (not the master) and the compiling worked fine; but after flahing to the ESP32 it blinking an nothing happens...

**Comment by nagyrobi** [comment]
What command did you use to make the clone?

**Comment by DSRocker** [comment]
I just downloaded the zip-file

**Comment by nagyrobi** [comment]
That's not cloning. You're not following the correct steps. Please read carefully:
- https://haswitchplate.github.io/openHASP-docs/0.6.2/compiling/local/
- https://haswitchplate.github.io/openHASP-docs/0.6.2/compiling/gitpod/

**Comment by DSRocker** [comment]
thanks! I'll do it correct :-)
another question: by compiling with gitpod I get the bin-file as version v0.7.0.bin

**Comment by nagyrobi** [comment]
yes

**Comment by DSRocker** [comment]
is the 0.7.0 better than the 0.6.2?! 
I would like to use my display horizontal (not vertical); should I change the values:
tft_rotation = 0      ; default rotation
tft_width = 240       ; default width / to 320
tft_height = 320      ; default height / and here to 240
in the lcd_config.ini

or is it enough to change this in the gui?

**Comment by nagyrobi** [comment]
try GUI first!

**Comment by DSRocker** [comment]
I just tried to compile again (git submodule update --init --recursive , ...) it's success, but the esp32 LED blinking and nothing happenning...

**Comment by nagyrobi** [comment]
OK that's another issue, this can be closed.
I suggest to go to Discorpd support forum https://discord.gg/S8Yrzey2 for faster replies.
