### ISSUE TITLE
Built-in Icons - The changes disappear after booting

### ISSUE THREAD

**Issue by DSRocker** [HASwitchPlate/openHASP#270]
On the 1. page I created a button:
{"page":1,"id":1,"obj":"btn","x":10,"y":25,"w":55,"h":55,"toggle":true,"text":"**\uE335**","text_font":32,"align":1,"comment":"Küche"}
{"page":1,"id":11,"obj":"label","x":70,"y":40,"w":130,"h":30,"text":"Switch_1","align":0,"text_font":16,"text_color":"black"}

After chaning the icon to: e.g. "\uF1E1" and while rebooting; you see the new icon! After 2 seconds the new icon disappers and the old one is visible again.

**Comment by fvanroie** [comment]
You need to check the log to see what is happening and what is causing the icon text to change...
This is usually an automation or retained mqtt message that makes the plate execute a new command...

**Comment by DSRocker** [comment]
thanks! I had to change the configuration in HA.

**Comment by fvanroie** [comment]
Great! I guess this issue can be closed.
