### ISSUE TITLE
Impossible to log in to Telnet if user/pass active

### ISSUE THREAD

**Issue by nagyrobi** [HASwitchPlate/openHASP#296]
### Perform all steps below and tick them with [x]
- [x] Check the related part of the [Documentation](https://haswitchplate.github.io/openHASP-docs/)
- [x] Update openHASP to the latest version
- [x] Reproduce the issue and describe all steps

### Describe the bug
If I set up a user and a password in the [web interface](https://haswitchplate.github.io/openHASP-docs/0.6.2/configuration/http/) I can't connect to Telnet anymore.

### To Reproduce
Ubuntu 20.04, gnome terminal:
```
~$ telnet 192.168.1.22
Trying 192.168.1.22...
Connected to 192.168.1.22.
Escape character is '^]'.

Username: 
Prompt > ���� �!�"�'��#admin
Password: 
Prompt > my_password_wdwed44
Authorization failed

Prompt > �
```
Windows, Putty:
![telnet_1](https://user-images.githubusercontent.com/1550668/151662724-2c8f1181-283e-4238-ae51-aa815d5d92dd.png)
![telnet_2](https://user-images.githubusercontent.com/1550668/151662728-b1229ad0-ca4c-45ca-80a4-9a7cbc93730e.png)

### Expected behavior
Be able to log in with user and password.

### Screenshots or video
See above.

**Comment by fvanroie** [comment]
> Still impossible to use Telnet with password set.

I'm able to use Putty to login with password set.
```
Welcome

Username: hasp
#

        open____ _____ _____ _____
          |  |  |  _  |   __|  _  |
          |     |     |__   |   __|
          |__|__|__|__|_____|__|
        Home Automation Switch Plate
        Open Hardware edition v0.6.4-dev

[15:36:44.591][77812/92152 15][50476/51072  2] TELN: Client login from 192.168.2.18
Prompt >
```
What output do you get when entering the credentials?
