### ISSUE TITLE
Inject the git short hash at build time and expose via the /info endpoint

### ISSUE THREAD

**Issue by kquinsland** [HASwitchPlate/openHASP#308]
**Is your feature request related to a problem? Please describe.**
Yes.  This comes from some of the recent regression testing that's taking place on discord right now. Right now, we are relying on manual notes / browser history to keep track of which bin file was flashed and then working backwards from there to figure out up to which GH commit(s) the bug(s) are not present.

**Describe the solution you'd like**

During each FW build, inject the short ID (truncated version of the full sha1 hash referring to the commit being used to build the fw) into the binary so that the git hash can be accessed via the `/info` url (and similar mqtt/telnet...)

I think platform.io already has most of the plumbing needed for this:

https://docs.platformio.org/en/latest/projectconf/section_env_build.html#projectconf-dynamic-build-flags

See the `Use Case: Create a “PIO_SRC_REV” macro with the latest Git revision` section.

There appears to be another (similar, but more sophisticated) approach here: 
https://community.platformio.org/t/how-to-build-got-revision-into-binary-for-version-output/15380

**Describe alternatives you've considered**

The alternatives are all less precise and therefore less useful.

**Additional context**

**Comment by nagyrobi** [comment]
I would add this even to the main page at the bottom...
