### ISSUE TITLE
Screen rotation using Lanbon L8 does not affect touch

### ISSUE THREAD

**Issue by unrealmodder** [HASwitchPlate/openHASP#318]
### Perform all steps below and tick them with [x]
- [x] Check the related part of the [Documentation](https://haswitchplate.github.io/openHASP-docs/)
- [x] Update openHASP to the latest version
- [x] Reproduce the issue and describe all steps

### Describe the bug
Using latest build from source using platformio.
If I rotate the display 90 degrees the touch interface remains at 0 degrees rotated whilst the UI is rotated 90 degrees. 

### To Reproduce
Use latest build from source then attempt to configure the rotation of the display through the web UI. 

### Expected behavior
Screen interface and touch overlay should rotate together.

**Comment by fvanroie** [comment]
This should fix it, can you try again please?

**Comment by unrealmodder** [comment]
> This should fix it, can you try again please?

Hello, sorry for the delay but can confirm its fixed. Thank you!
