### ISSUE TITLE
Support for backlight on Makerfab ESPTFT35(CA)

### ISSUE THREAD

**Issue by mmccool** [HASwitchPlate/openHASP#335]
**Is your feature request related to a problem? Please describe.**
Currently openHASP can't control the backlight on the [Makerfabs ESPTFT35(CA)](https://www.makerfabs.com/esp32-3.5-inch-tft-touch-capacitive-with-camera.html) board.  It's true that the standard board as-shipped is always-on, BUT backlight control can (theoretically) be enabled by soldering two pads together (marked R31 on the board).  Technically a 0 Ohm resistor should be used, but a blob of solder or a small wire would (probably) also do the trick.  This connects GPIO1 to the backlight control on the display, which means you cannot use TX in the UART (uses the same pin) and therefore disables serial debugging, but no big deal.  See https://github.com/Makerfabs/Project_Touch-Screen-Camera/issues/8

**Describe the solution you'd like**
A flag or some build-time configuration option (disabled by default) to allow backlight control using PWM on GPIO1.

**Describe alternatives you've considered**
Well, I could go in and try to hack the code myself, and then try to upstream it to benefit others, but I'm lazy.  If someone points me in the right direction though I can test a solution.  I happen to have two boards so I will modify one and leave the other one alone for test purposes.  I already have openHASP running on the board and integrated with Home Assistant.

**Additional context**
This page should also be updated to note that backlight control can be added with a little soldering and configuring, assuming it can be made to work: https://openhasp.haswitchplate.com/0.6.2/devices/makerfabs-tft-touch/

**Comment by fvanroie** [comment]
I discovered that resistor in the schematics but didn't find it very useful at the time. While technically it can be done, I haven't tested this as I'm not *that* precise with a soldering iron.

It's not just the debug output as flashing of the ESP32 over UART could be affected too. I'm not sure if that will still work after the resistor is soldered on. Granted that you can upload firmware via OTA but it makes recovery a lot harder. Have you tested flashing the ESP32 with the blob on?

Before delving into the code, I would suggest:
- Please try [openHASP 0.6.3-rc1](https://github.com/HASwitchPlate/openHASP/discussions/334). It has the option to disable the Serial Port from the Debug Settings
- The ESP32 will still output some bootloader junk to the pin on boot, but that shouldn't be an issue...
- There is no Web UI option to set `GPIO1` for backlight atm, but you can use the `config/gui` commands:
- Publish `{"bckl":1}` to topic `hasp/<plate>/config/gui` or `api/config/gui` [REST endoint](https://github.com/HASwitchPlate/openHASP/issues/246#issuecomment-1024829360)
- Reboot

I haven't tried *the blob*, but that could work. The Web UI won't reflect the selected backlight pin, but that's window dressing which we can address if it works.

**Comment by fvanroie** [comment]
Did you have a chance to test UART with the backlight blob on?
