### ISSUE TITLE
No wifi reconnect on lanbon_l8_ota_v0.6.4-dev_14ba13e.bin after wifi access point reboot.

### ISSUE THREAD

**Issue by juan11perez** [HASwitchPlate/openHASP#385]
### Describe the bug
Following (wifi) access point reset, the plate will not reconnect to wifi. 

### To Reproduce
This is happening with the development (lanbon_l8_ota_v0.6.4-dev_14ba13e) bin. 
Install dev firmware. Disconnect wifi to plate, reconnect wifi.
To rejoin wifi a power cycle is required

### Expected behaviour
On (wifi) access point returning to operation, plate reconnects to wifi. This bug is not present on 6.3. i.e the plate will reconnect as it continuously reboots until re-connection. On 6.4dev the plate seems to remain idle.

**Comment by fvanroie** [comment]
Please test commit 80bda2c from the [latest build](https://github.com/HASwitchPlate/openHASP/actions/runs/3164515352).

**Comment by juan11perez** [comment]
@fvanroie 
I installed lanbon_l8_ota_v0.6.4-dev_80bda2c.bin. Disabled wifi, plate displayed 'offline'. Enabled wifi and the plate reconnected.
I think it's working well now.
Thank you very much

**Comment by fvanroie** [comment]
Thanks for the report and testing.

**Comment by juan11perez** [comment]
@fvanroie thank you for this excellent component.
