### ISSUE TITLE
Sunton 7 inches screen just flicker after flashing

### ISSUE THREAD

**Issue by primeroz** [HASwitchPlate/openHASP#431]
## Questions

Hi, i know this is in beta so not expecting anything but i thought i would bring up that flashing the Sunton screen 7 inches from at least `ssunton-8048s070c_full_16MB_v0.6.4-dev_5f376e2.bin`  up to the lastest version availble in nightly `sunton-8048s070c_full_16MB_v0.7.0-dev_aa1f4e7.bin` result in a `screen flickering` and nothing else. 

https://user-images.githubusercontent.com/2085772/219741325-4274f1a6-b9c5-4ac4-8cfd-1aeedce84315.mp4

Sometimes i can see the openHasp logo 

I can erase the flash ( by running the command at the right itme ) and flash other images, i went back up to `sunton-8048s070c_full_16MB_v0.6.4-dev_5f376e2.bin` but they all have the same issue. 

I would go back more but the assets from github have expired so i can't go backward anymore than that 

The `Stock` UI was working so i don't think is a problem with the actual device 

Is there a known working version i can flash so i can try openHasp out ? 

thanks

**Comment by primeroz** [comment]
I am really new to esp32 stuff. I was powering it from a usb hub connected to my computer right after flashing it. 

I will try with a wall socket adapter.

**Comment by fvanroie** [comment]
The 7" is quite power hungry, so the hub might fail to provide the minimal power. A power brick or powered USB hub should be fine. Flaky USB cables can also pose an issue, try swapping that too if the issue persists.

**Comment by primeroz** [comment]
you were right, moved to the powered usb hub and it works . sorry for opening such a stupid issue :pray:

**Comment by fvanroie** [comment]
No worries. 😃 
Have fun with the device!
