### ISSUE TITLE
MQTT Port is not saved

### ISSUE THREAD

**Issue by econnie323** [HASwitchPlate/openHASP#434]
### Perform all steps below and tick them with [x]
- [X] Check the related part of the [Documentation](https://haswitchplate.github.io/openHASP-docs/)
- [X] Update openHASP to the latest version
- [X] Reproduce the issue and describe all steps

### Describe the bug
MQTT Port is not saved in openHASP 0.7.0-dev (265f9c4) for WT32-SC01 Plus

### To Reproduce

Change the MQTT Port and Save Settings. Then reopen the MQTT Settings.

### Screenshots or video

<img width="610" alt="Screenshot 2023-02-26 alle 14 33 50" src="https://user-images.githubusercontent.com/9267309/221414233-d3fb62d2-461a-4324-bd10-4690b5bfac20.png">

**Comment by fvanroie** [comment]
Thanks for reporting! It is fixed in the latest dev build (Actions tab).
