### ISSUE TITLE
Take a Screenshot

### ISSUE THREAD

**Issue by markusressel** [HASwitchPlate/openHASP#441]
**Is your feature request related to a problem? Please describe.**
For showing off openHASP and configurations a user has come up with, it would be really nice to be able to take a screenshot on the device itself, instead of having to take a photo.

**Describe the solution you'd like**
Provide a button on the webserver to take a screenshot and download it immediately.

**Describe alternatives you've considered**
Provide a command to save a screenshot on the internal storage, allowing the user to download it using the API or web file browser.

**Additional context**
N/A

**Comment by htvekov** [comment]
You can already download/copy an image directly from the web interface.
Just right click on the image to copy or download it.
![image](https://user-images.githubusercontent.com/45469813/222958059-1fd4a418-dd0a-4d9a-8d6d-096217159a21.png)

![image](https://user-images.githubusercontent.com/45469813/222958147-43e5c90c-5fe8-4d7d-99cb-7b2932f0d694.png)

**Comment by markusressel** [comment]
Whoops not sure how I was able to miss that one! 😅 
Thx for the info! ❤️

**Comment by fvanroie** [comment]
The link `http://<ip>/screenshot?q=0` should give you a BMP file back that can be saved and opened in any image editor.
