### ISSUE TITLE
Multi page functionality on large screens

### ISSUE THREAD

**Issue by Asbjoern** [HASwitchPlate/openHASP#443]
On large displays like the Sunton 7" it can make sense to split the screen into two or more and show several pages independently.
You might want weather or mediaplayer on right side and still be able to switch pages on the left.
I know similar functionality can be achieved by hiding and unhiding P0 objects but real multi page is a lot more user friendly

**Comment by nagyrobi** [comment]
Like navigating through pages of a book?

**Comment by Asbjoern** [comment]
Possibly...
I my case I want on the right side of screen to switch between mediaplayer and weather station information. And om the left controls for different parts of the house on several pages.
