### ISSUE TITLE
Sunton ESP32-8048S050C don't boot

### ISSUE THREAD

**Issue by xtimmy86x** [HASwitchPlate/openHASP#448]
### Perform all steps below and tick them with [x]
- [x] Check the related part of the [Documentation](https://www.openhasp.com/)
- [x] Update openHASP to the latest version
- [X ] Reproduce the issue and describe all steps

### Describe the bug
After correctly flash the nightly firmware the screen don't boot and flash blank repeatly

### To Reproduce
Flash nightly firmware

### Expected behavior
The device boot up but don't do correctly

**Comment by fvanroie** [comment]
@xtimmy86x Is it working and did you find the issue?

**Comment by xtimmy86x** [comment]
> 

Yes, it was a bad power supply, i did the test with the panel connected to pc and doesn't boot,
but when i connect to an external power supply it boot correctly
