### ISSUE TITLE
windows.h not found when building for win32

### ISSUE THREAD

**Issue by Ierlandfan** [HASwitchPlate/openHASP#451]
### Perform all steps below and tick them with [x]
- [x] Check the related part of the [Documentation](https://www.openhasp.com/) 
- [x] Update openHASP to the latest version
- [x] Reproduce the issue and describe all steps

### Describe the bug

When creating a windows build (Win32,  windows_sdl_64bits) (For development) platformio  (Online with Gitpod or Linux with platformio ) complains about a few things

-mconsole: (Command not found / unknown command ) (That can be hashed out)
windows.h not found. ( I can not seem to find the package / library where it is , I guess Paho MQTT needs it?

So I reverted to  a Linux build (linux_sdl_64bits) for now but there I don't know where I can put pages.jsonl or whether it is able to connect to a network. 

windows.h not found 

### To Reproduce

sudo platformio run 
........
Compiling .pio/build/windows_sdl_64bits/.pio/libdeps/windows_sdl_64bits/paho/src/Base64.o
.pio/libdeps/windows_sdl_64bits/paho/src/Base64.c:21:10: fatal error: windows.h: No such file or directory

*****************************************************************
* Looking for windows.h dependency? Check our library registry!
*
* CLI  > platformio lib search "header:windows.h"
* Web  > https://registry.platformio.org/search?q=header:windows.h
*
*****************************************************************

   21 | #include <windows.h>
      |          ^~~~~~~~~~~
compilation terminated.
```


### Expected behavior
That win32 builds can be built succesfully

**Comment by fvanroie** [comment]
Make sure you install and configure MSYS2 correctly: https://www.openhasp.com/0.7.0/firmware/compiling/local/#native-windows-build
