### ISSUE TITLE
Compile error for lolin-d32-pro_ili9341 related to src/mqtt/hasp_mqtt_ha.cpp

### ISSUE THREAD

**Issue by jgoldwein** [HASwitchPlate/openHASP#466]
### Perform all steps below and tick them with [x]
- [x] Check the related part of the [Documentation](https://www.openhasp.com/)
- [x] Update openHASP to the latest version
- [x] Reproduce the issue and describe all steps
### Describe the bug
Compile error using linux cli platformio compile (pio run) at end of compile process when Home Assistant autodiscovery (#define HASP_USE_HA) is enabled in user_config_override.h
=====
Error at end of compile process:
=====
```
.../.platformio/packages/toolchain-xtensa-esp32@8.4.0+2021r2-patch5/bin/../lib/gcc/xtensa-esp32-elf/8.4.0/../../../../xtensa-esp32-elf/bin/ld: .pio/build/lolin-d32-pro_ili9341/src/mqtt/hasp_mqtt_ha.cpp.o:(.literal._Z22mqtt_ha_add_device_idsRN11ArduinoJson7V6211PD12JsonDocumentE+0x24): undefined reference to `mqttNodeTopic'
collect2: error: ld returned 1 exit status
*** [.pio/build/lolin-d32-pro_ili9341/firmware.elf] Error 1
```
-->

### To Reproduce

```
in user_config_override.h uncomment:
#define HASP_USE_HA 
```
-->

### Expected behavior

Successful compile
-->

### Screenshots or video

Note that the code compiles correctly with the following change to src/mqtt/hasp_mqtt_ha.cpp:
```
--- a/src/mqtt/hasp_mqtt_ha.cpp
+++ b/src/mqtt/hasp_mqtt_ha.cpp
@@ -85,6 +85,7 @@ void mqtt_ha_add_device_ids(JsonDocument& doc)
     device[FPSTR(FP_MQTT_HA_MODEL)]        = F(PIOENV);
     device[FPSTR(FP_MQTT_HA_MANUFACTURER)] = F(D_MANUFACTURER);

+    std::string mqttNodeTopic;**
     doc[F("~")] = mqttNodeTopic;
 }
```
-->

**Comment by fvanroie** [comment]
HASP_USE_HA isn't supported anymore.
