### ISSUE TITLE
Checkboxes: Child component not positioned relative to parent

### ISSUE THREAD

**Issue by matsekberg** [HASwitchPlate/openHASP#467]
### Describe the bug
Child checkbox components are not positioned relative to their parent component. Checkbox relative to tab component works. Or is it that grouping cannot be recursive?

### To Reproduce

```
{"page":5}
{"id":1,"obj":"tabview","btn_pos":1,"y":40, "val":0}
{"id":100,"obj":"tab", "parentid":1,"text":"Avfärd"}
{"id":101,"obj":"tab","parentid":1,"text":"Ankomst"}

{"id":201,"obj":"checkbox","x":0,"y":0,"parentid":100,"text_font":20, "text":"Stödben och kilar"}
{"id":202,"obj":"checkbox","x":0,"y":0,"parentid":201,"text_font":20, "text":"Elkabel borttagen"}
{"id":203,"obj":"checkbox","x":0,"y":0,"parentid":202,"text_font":20, "text":"Luckor/skåp låsta"}
{"id":204,"obj":"checkbox","x":0,"y":0,"parentid":203,"text_font":20, "text":"Takluckor stängda"}
```

I tried to use groupid to stack checkboxes in a column.
The first checkbox (201) is placed relative to the tab (parentid=100).
The second checkbox is positioned relative to the first one (parentid=201), but in the display it is placed on the same row but to the right of the first checkbox.

### Expected behavior

Checkboxes in the example should be placed in a column, not a row.

### Screenshots or video
![image](https://user-images.githubusercontent.com/4611611/231999722-21b70776-f434-45b3-bb4b-880785cf4e8f.png)

**Comment by fvanroie** [comment]
> I tried to use groupid to stack checkboxes in a column.

To achieve this try;
```json
{"page":1}
{"id":1,"obj":"tabview","btn_pos":1,"y":40, "val":0}
{"id":100,"obj":"tab", "parentid":1,"text":"Avfärd"}
{"id":101,"obj":"tab","parentid":1,"text":"Ankomst"}

{"id":201,"obj":"checkbox","x":5,"y":5,"parentid":100,"text_font":20, "text":"Stödben och kilar"}
{"id":202,"obj":"checkbox","x":5,"y":40,"parentid":100,"text_font":20, "text":"Elkabel borttagen"}
{"id":203,"obj":"checkbox","x":5,"y":75,"parentid":100,"text_font":20, "text":"Luckor/skåp låsta"}
{"id":204,"obj":"checkbox","x":5,"y":110,"parentid":100,"text_font":20, "text":"Takluckor stängda"}
```

A child is positioned *inside* the parent and relative to its parent.
Nesting the checkboxes like that is not supported. Align them with the `tab` id `100` instead.

![image](https://user-images.githubusercontent.com/15969459/232057716-8f44c3d4-80bc-48e0-ad8c-672777bf2d6e.png)

**Comment by matsekberg** [comment]
Ok the keyword is inside. My goal was to move a block of components at the same time.
With the base object I guess I could achieve this by placing the children inside a base object

**Comment by fvanroie** [comment]
Indeed, the base object can serve the purpose of a container for positioning multiple children inside it.
