### ISSUE TITLE
Touch not working on Sunton ESP32-2432S028r

### ISSUE THREAD

**Issue by matsekberg** [HASwitchPlate/openHASP#472]
### Describe the bug
Touch not working on Sunton ESP32-2432S028r

### To Reproduce
When I got the display touch was working with the flashed demo.
Flashed esp32-2432s028r_full_4MB_v0.7.0-rc4_f76dee8.bin and configured wifi. Uploaded my page and voila, no touch whatsoever is working. Works on ESP32-8048S050 and ESP32-3248...

### Expected behavior
Touch to work.

### Screenshots or video
N/A

**Comment by matsekberg** [comment]
My bad. I didnt do calibration first :(

**Comment by fvanroie** [comment]
No problem. I was about to look into this, but good to hear it worked out.
