### ISSUE TITLE
MQTT TLS and long user/password

### ISSUE THREAD

**Issue by webfrank** [HASwitchPlate/openHASP#488]
### Perform all steps below and tick them with [x]
- [X] Check the related part of the [Documentation](https://www.openhasp.com/)
- [X] Update openHASP to the latest version
- [X] Reproduce the issue and describe all steps

### Describe the bug
I tried to connect to a TLS enabled MQTT broker but it doesn't work, the board continues to reboot.

I tried to connect to a standard MQTT broker with a long (a token) username or password but it get truncated and does not connect

### To Reproduce
Use a TLS enabled MQTT broker (port 8883) or try to connect to a plain MQTT broker with a long username or password.

### Expected behavior
Successful connection

**Comment by fvanroie** [comment]
MQTT TLS isn't suported atm. Please define how long username/password you need. The lengths are adjustable if you compile the firmware yourself:

```c
// Lengths
#ifndef MAX_PASSWORD_LENGTH
#define MAX_PASSWORD_LENGTH 64
#endif
#ifndef MAX_USERNAME_LENGTH
#define MAX_USERNAME_LENGTH 32
#endif
#ifndef MAX_HOSTNAME_LENGTH
#define MAX_HOSTNAME_LENGTH 128
#endif
```
