### ISSUE TITLE
Support for LVGL charts

### ISSUE THREAD

**Issue by matsekberg** [HASwitchPlate/openHASP#501]
I would like to have the ability to draw graphs using the LVGL chart component.
https://docs.lvgl.io/master/widgets/chart.html

**Comment by fvanroie** [comment]
An update to LVGL v8 (or v9) is required first, so don't expect this to be implemented any time soon...

**Comment by koverg70** [comment]
Does anyone already working on LVL v8 / v9 porting? If yes, on which branch or fork?

**Comment by fvanroie** [comment]
Not that I am aware of, feel free to test and report back.
