### ISSUE TITLE
GitPod compile error by wrong env.

### ISSUE THREAD

**Issue by exotsk** [HASwitchPlate/openHASP#510]
### Perform all steps below and tick them with [x]
- [ ] Check the related part of the [Documentation](https://www.openhasp.com/)
- [ ] Update openHASP to the latest version
- [ ] Reproduce the issue and describe all steps

### Describe the bug

After trying compile dev by GitPod, after selecting by uncomment in platformio_override.ini my env i get wrong env error lijke this:
gitpod /workspace/openHASP $ platformio run
UnknownEnvNamesError: Unknown environment names 'sunton-3248s035r_4MB'. Valid names are 'esp32dev-mrb3511, az-touch-mod-esp32_ili9341_8MB, ttgo_esp32_poe-ili9341, my_custom_build, d1-r32-unoshield_ili9486_adc, lolin-d32-pro_ili9341, az-touch-mod-esp32_ili9341_4MB, d1-mini-esp32_ili9341, esp32-one_st7796, d1-r32-unoshield_ili9341_adc'

### To Reproduce

Compile

![image](https://github.com/HASwitchPlate/openHASP/assets/54969124/48256930-63aa-4f69-be29-58098c82bf94)
![image](https://github.com/HASwitchPlate/openHASP/assets/54969124/faf20fe2-1f29-496f-91b9-b5b74410d7ab)

**Comment by exotsk** [comment]
my mistake. i don`t select ini file.

**Comment by fvanroie** [comment]
No problem, good to hear you figured it out. Have fun!
