### ISSUE TITLE
Sunton 3248s035r touch stopped working at 0.7rc7

### ISSUE THREAD

**Issue by exotsk** [HASwitchPlate/openHASP#514]
Sunton 3248s035r touch stopped working at 0.7rc7 (esp32-3248s035r_full_4MB_v0.7.0-rc7_19ed334). After firmware via USB full firstmare with wipe data, the touchscreen does not work. I flashed the rc5_ota (esp32-3248s035c_ota_v0.7.0-rc5_dd0c862), the touchscreen immediately started working.
I cant make a calibration, plate freeze when try it. can`t make first wi-fi set by the touch

but sunton 8048s050c with sunton-8048s050c_ota_v0.7.0-rc7_19ed334 works well.

**Comment by fvanroie** [comment]
- `esp32-3248s035c` is for **C**aptive Touchscreens.
- `esp32-3248s035r` is for **R**esistive Touchscreens.

You need to flash the correct [firmware version (with trailing R/C)](https://nightly.openhasp.com/) for your hardware.

**Comment by exotsk** [comment]
OMG, my bad, it was stupid =))

**Comment by exotsk** [comment]
OMG, my bad, it was stupid =))
