### ISSUE TITLE
Support the CORE2's touch buttons

### ISSUE THREAD

**Issue by Aaroneisele55** [HASwitchPlate/openHASP#545]
**Is your feature request related to a problem? Please describe.**
The touch buttons are currently unsupported on the M5Stack Core2
**Describe the solution you'd like**
I would like the three touch buttons of the Core2 to be available in the HA Integration and on MQTT
**Describe alternatives you've considered**
No alternatives

**Comment by fvanroie** [comment]
Duplocate of  M5Stack Core2 Buttons #368
