### ISSUE TITLE
nightly.openhasp links don't work for ttgo-t7-v1.5_ili9341

### ISSUE THREAD

**Issue by xviti** [HASwitchPlate/openHASP#599]
Hi all:
https://nightly.openhasp.com/firmware/ttgo-t7-v1.5_ili9341_ota_v0.7.0-rc9_b7283c9.bin
https://nightly.openhasp.com/firmware/ttgo-t7-v1.5_ili9341_full_4MB_v0.7.0-rc9_b7283c9.bin
these links don't work, get 404 error

**Comment by fvanroie** [comment]
Thanks for reporting. There was a typo in the firmware file. This is now fixed for TTGO T7 v1.5.
