### ISSUE TITLE
Event payload "string" should be a valid JSON

### ISSUE THREAD

**Issue by smcgann99** [HASwitchPlate/openHASP#637]
### Perform all steps below and tick them with [x]
- [X] Check the related part of the [Documentation](https://www.openhasp.com/)
- [X] Update openHASP to the latest version
- [X] Reproduce the issue and describe all steps

### Describe the bug

Event payload "string" should be valid JSON, currently it is not checked, allowing for none escaped characters eg newline, to prevent downstream parsing.

### To Reproduce

adding this to a matrix button -
```json
  options: [`#FCFF12    \uE2DC #\nHome`, `#FF1256    \uE70E #\nAway`, `#125AFF    \uE2E3 #\nNight`, `#0FFF50  \uEFC6 #\nOff`]
```

### Expected behavior

special characters need to be escaped

### Screenshots or video

[https://discord.com/channels/538814618106331137/692393568266092617/1207477077432078437](url)

**Comment by fvanroie** [comment]
This should now be fixed, please test it thoroughly, especially with tags and text.

**Comment by smcgann99** [comment]
Text looks OK but tag gives me - tag: "{"type":"alarm"}" instead of tag:{"type":"alarm"}

**Comment by fvanroie** [comment]
Thanks, 3rd time is a charm.
