### ISSUE TITLE
Configurable Idle page number

### ISSUE THREAD

**Issue by hmorkemo** [HASwitchPlate/openHASP#645]
**Is your feature request related to a problem? Please describe.**
I'm looking for a simplification of the programming of my hasp panels.

**Describe the solution you'd like**
Instead of the screen just going blank after the timeout period, I would like to set a specific page number as the idle screen.
e.g. { page: 0, idlepage: 12 }
This would simplify automations on the HA side.
It could even be nice (maybe) to set this, and the timeout interval, individually on each page: { page: 2, idlepage: 11, timeout: 10 }

**Describe alternatives you've considered**
The alternative way is to handle this in automations in HA, which of course is possible. But doing as much as possible of the tasks "everyone" needs to do in one place is always a good thing.

**Comment by fvanroie** [comment]
How about u[sing the `idle_long.cmd` script](https://www.openhasp.com/0.7.0/commands/scripts/) to return to the homepage?
