### ISSUE TITLE
Animation effects and smooth transitions

### ISSUE THREAD

**Issue by xiasi0** [HASwitchPlate/openHASP#665]
Will advanced special effects such as animation effects and smooth transitions be added to future versions?

**Comment by fvanroie** [comment]
What do you mean by Animation effects and smooth transitions?

**Comment by xiasi0** [comment]
> 动画效果和平滑过渡是什么意思？


https://github.com/HASwitchPlate/openHASP/assets/129178072/d4d65806-770f-4f4c-8341-f3e53b04725b

This is not implemented by ESP32S3. I understand that the performance of ESP32 may not be sufficient, but will future versions have similar effects?

**Comment by fvanroie** [comment]
There are currently no plans to add this sort of animations to openHASP, but maybe you can implement them by using the low level LVGL api's.
