### ISSUE TITLE
please allow more than 8 gpios

### ISSUE THREAD

**Issue by wildblue** [HASwitchPlate/openHASP#669]
**Is your feature request related to a problem? 
i can not configured all gpios of my Display Board 

**Describe the solution you'd like**
More GPIOS than 8 in/out.

**Describe alternatives you've considered**
Sllow 8 IN and 8 OUT

**Additional context**
very important, otherwise the whole Project gets useless for me.

**Comment by fvanroie** [comment]
Try setting `HASP_NUM_GPIO_CONFIG` in your board configuration.

**Comment by fvanroie** [comment]
Did this method work out for you?
