### ISSUE TITLE
No Ampersand sign for entering wifi passwords

### ISSUE THREAD

**Issue by NateChurch** [HASwitchPlate/openHASP#672]
### Perform all steps below and tick them with [x]
- [x] Check the related part of the [Documentation](https://www.openhasp.com/)
- [x] Update openHASP to the latest version
- [x] Reproduce the issue and describe all steps

### Describe the bug

When performing a manual entry of a wifi password using the touch screen keyboard, there is no ampersand(&) sign on the symbols page. 

### To Reproduce

1. Click the *Factory Reset* from the openHASP menu.
2. touch the screen and attempt to configure the wifi using the on-screen keyboard

### Expected behavior
There is an ampersand on the on-screen keyboard. This looks like a limitation to the LVGL library.

**Comment by fvanroie** [comment]
This character was missing from the virtual keyboard upstream. This has been added and should be available in [the latest build](https://github.com/HASwitchPlate/openHASP/actions/runs/8283081859).

**Comment by fvanroie** [comment]
The ampersand is now available in the symbols:

![image](https://github.com/HASwitchPlate/openHASP/assets/15969459/b132276b-1e10-40b7-840c-fa60236a5a47)
