### ISSUE TITLE
Sunton ESP-32-8048S070 Backlight dimming is not working

### ISSUE THREAD

**Issue by DukemFIVE** [HASwitchPlate/openHASP#691]
### Perform all steps below and tick them with [x]
- [ x] Check the related part of the [Documentation](https://www.openhasp.com/)
- [x ] Update openHASP to the latest version
- [x ] Reproduce the issue and describe all steps

### Describe the bug
If I try to dim the display using HomeAssistant (e.g. to 50% brightness) then the display goes completely black.
I have to set the brightness to over 85%, then the display will turn on again, but at 100%. If I choose a brightness below 85% then it becomes completely dark. The threshold value of 85% is not always consistent, sometimes it is 81 or 83.
I also tried to lower the startup brightness in the config, I have the same problem there.
I use the V07RC11 with the Sunton ESP-32-8048S070 (Touch)

### To Reproduce
Set the backlight to lower then 80%

### Expected behavior
The backlight dims to the set percentage

### Screenshots or video
Display ist on with 100% brightness
![image](https://github.com/HASwitchPlate/openHASP/assets/119198285/d0880650-cb86-42d0-982f-04a63dc2d4b1)

Display ist off with 0% brightness
![image](https://github.com/HASwitchPlate/openHASP/assets/119198285/13f00b37-0f7c-4bd4-a891-3cf10bdb2eb5)

**Comment by WarC0zes** [comment]
Hi,
I've no problem with firmware 0.7.0-rc11 677e8cc and openHASP integration v0.7.2.


openHASP
--
Version | 0.7.0-rc11 677e8cc
Build DateTime | Feb 26 2024 21:04:04 UTC
Environment | sunton-8048s070c_16MB
Uptime | 8d 3h 10m 11s

![image](https://github.com/HASwitchPlate/openHASP/assets/91471397/a4048f9b-83b7-4308-99c5-b7cba4f2485f)

**Comment by DukemFIVE** [comment]
Hi,

I have the 0.7.2 installed (reinstalled it already)
![image](https://github.com/HASwitchPlate/openHASP/assets/119198285/db3c6360-476f-41ea-8b4b-6c152b72e1aa)

![image](https://github.com/HASwitchPlate/openHASP/assets/119198285/2a2198c9-099a-465f-bc47-965c84bcb596)
![image](https://github.com/HASwitchPlate/openHASP/assets/119198285/12977c3a-a6c9-4308-8c14-d159e9614027)

How can I check if there is a hardware defect?

**Comment by WarC0zes** [comment]
You have the HA core up to date ?
v2024.3.3 ?

**Comment by DukemFIVE** [comment]
Yes v2024.3.3

**Comment by marsman7** [comment]
which gpio pin is used to control the backlight on the sunton?

**Comment by smcgann99** [comment]
BACKLIGHT_FREQUENCY needs to be around 100 for that screen

**Comment by fvanroie** [comment]
Please test the l[atest Sunton builds](https://github.com/HASwitchPlate/openHASP/actions/runs/8584608794) from the Action tab.

**Comment by smcgann99** [comment]
Checked and working OK on my sunton-8048s070c_16MB

**Comment by DukemFIVE** [comment]
Works great ! Thank you !!
