### ISSUE TITLE
opneHASP support for Pyportal

### ISSUE THREAD

**Issue by tome88** [HASwitchPlate/openHASP#710]
Hi there, wanting to know if there is an easy way (or might be a way in the future) to have openHASP available for pyportal/pyportal Titano systems (they run on an ATSAMD51J20 and don't seem to be compatible at the moment)

**Comment by tome88** [comment]
> openHASP does _not_ support the ATSAMD51J20 microcontroller. There are a few dozens of ESP32 devices that can run openHASP to choose from. If your really wanted to port the source code to a new MCU, I guess it _could_ eventually work... the question is if it's worth the time and effort, since most devices only cost a coupla bucks nowadays.

thanks for the quick reply @fvanroie

**Comment by fvanroie** [comment]
Is this something you'll be pursuing and actively working towards? Or can this issue be closed?
