### ISSUE TITLE
mqtt control

### ISSUE THREAD

**Issue by fifa255** [HASwitchPlate/openHASP#716]
Does openhasp support publishing to mqtt topics?  

I would like to control some mqtt devices directly from the display rather than having to be dependent on homeassistant. Is this a possibility with openhasp currently?

**Comment by marsman7** [comment]
openhasp now already sends mqtt commands when a control is activated.

https://www.openhasp.com/0.7.0/commands/mqtt/

**Comment by fvanroie** [comment]
openHASP was concieved to be controlled by an Home Automation system. There isn't any intelligence or coding that happens on the device. So, you can add your [custom code](https://www.openhasp.com/0.7.0/firmware/compiling/custom/) to the firmware to make it do what you want...

A controller would need to know the topics but also the format of the messages to send and respond too. This is very specific for each device, so you need custom event handlers for that.
