### ISSUE TITLE
Makerfabs ESP32-S3 WROOM1 3,5 TFT SPI is not supported

### ISSUE THREAD

**Issue by dersch81** [HASwitchPlate/openHASP#728]
https://www.openhasp.com/0.7.0/hardware/makerfabs/esp32-s3-spi-tft-touch/

![image](https://github.com/HASwitchPlate/openHASP/assets/13754891/3e5c25be-606d-4a90-b443-5061f386325f)

![image](https://github.com/HASwitchPlate/openHASP/assets/13754891/ba8043cb-725b-4819-93ba-bc1f6d562eef)

![image](https://github.com/HASwitchPlate/openHASP/assets/13754891/d70dac06-8b75-4202-96a5-6fd0c237858a)

**Comment by marsman7** [comment]
The same board works 100 percent for me. Check your settings.

**Comment by marsman7** [comment]
does the file exist in your system and is it compiled with ?

user_setups/esp32s3/makerfabs-s3-tft35-spi.ini

**Comment by dersch81** [comment]
I did not try to complie it by myself. I tried the web esp flasher with
provided precomplied binaries.

Martin ***@***.***> schrieb am Di., 21. Mai 2024, 07:59:

**Comment by marsman7** [comment]
Ich habe den ESP-Flasher noch nie verwendet. Das selbst Kompilieren läuft ohne Fehler durch.

**Comment by fvanroie** [comment]
I added the Makerfabs S3 to https://nightly.openhasp.com/ please try it there.

**Comment by dersch81** [comment]
> I added the Makerfabs S3 to https://nightly.openhasp.com/ please try it there.

Thanks for adding. But it fails with the same error:

![image](https://github.com/HASwitchPlate/openHASP/assets/13754891/b8f9c723-5e56-43ae-8ec2-f155ecd1f5f7)

**Comment by fvanroie** [comment]
Thanks, I must have overlooked something.. please try again now.

**Comment by dersch81** [comment]
Yes, it is working. Many thanks

fvanroie ***@***.***> schrieb am Di., 28. Mai 2024, 21:53:
