### ISSUE TITLE
Unable to build full version 7.0

### ISSUE THREAD

**Issue by haaxema** [HASwitchPlate/openHASP#731]
Hi,

I am trying to loclay build V7.0RC12 using VSCode/PIO for my WT32SC01
It works fine, but I only get the OTA bin, not the Full version.
As I am trying to upgrade from 6.3 I need the Full bin to do a serial upload.

Any thoughts?

Martin

**Comment by fvanroie** [comment]
You can download it from https://nightly.openhasp.com/

**Comment by fvanroie** [comment]
The issue is most likely that you are using Windows and pip is out-of-data or the PySerial library is missing...

If so, you can fix it by running these two commands in order:
```cmd
C:\Users\<username>\.platformio\python3\python.exe -m ensurepip --upgrade
C:\Users\<username>\.platformio\python3\python.exe -m pip install Pyserial
```

Make sure to replace `<username>` with your actual username. That fixed the issue for me.

**Comment by fvanroie** [comment]
Is this problem resolved now?
