### ISSUE TITLE
Guition ESP32-S3-4848S040 rc11 vs rc12

### ISSUE THREAD

**Issue by Bzhmic** [HASwitchPlate/openHASP#755]
I'm using a Guition ESP32-S3-4848S040

with v0.7.0-rc12 and in comparison with rc11

GPIO 38 is no longer available in the display setting choice list for the backlight (you can put it manually in config.json)
the antiburn blurs the screen (bug)
the backlight dimmer works well now.

Have a good day

Thank you.

**Comment by fvanroie** [comment]
Duplicate for https://github.com/HASwitchPlate/openHASP/issues/751
