### ISSUE TITLE
Language support

### ISSUE THREAD

**Issue by dl5dla** [HASwitchPlate/openHASP#782]
Hi,
I have the following entry in pages.jsonl to show the date on each page:
`{"page":00,"id":02,"obj":"label","x":000,"y":000,"w":480,"h":032,"text":"Sun, 18. Jan 2024","template":"%a, %e. %b %Y","text_color":"#FFFFFF","align":"center", "enabled":0, "text_font":24}`

Instead of the English version ("Sun, 18. Jan 2024") I would like to switch to the German version ("So, 18. Jan 2024"), but I did not find any option to use the German translation. Is this somehow possible?

<del>And, more general, is it possible to switch the gui to German language? I used the web installer (https://nightly.openhasp.com/) to install openHASP (0.7.0-rc12 cd34d89), but I did not find any option in the configuration to change the language afterwards.</del>. Answered here: ([https://github.com/HASwitchPlate/openHASP/discussions/784](url))

BTW, I am using openHASP without Homeassistant.

Regards,
Peter

**Comment by fvanroie** [comment]
afaik ESP-IDF implements the `strftime` function in English only.
You need to implement a custom `strftime` function for other languages.
