### ISSUE TITLE
Spaces replaced by TAB in file editor

### ISSUE THREAD

**Issue by matsekberg** [HASwitchPlate/openHASP#788]
### Perform all steps below and tick them with [x]
- [x] Check the related part of the [Documentation](https://www.openhasp.com/)
- [x] Update openHASP to the latest version
- [x] Reproduce the issue and describe all steps

### Describe the bug
When I edit a file on an OpenHasp device using the file editor and enter multiple spaces, they are replaced by TAB character(s)

### To Reproduce
Just edit a file, enter  multiple spaces and the use the arrow keys to back go left. The cursor will jump rather than take one space-step at a time.

### Expected behavior
No TABs stored

### Screenshots or video

First I erase the spaces, then enter new spaces and lastly walks left with arrow keys. And the cursor jumps.

https://github.com/user-attachments/assets/91cd0b04-968a-4973-b0a4-c7877d12586c

**Comment by matsekberg** [comment]
Just noticed that I can type Oprion-Space on a Mac keyboard to enter hard spaces and they are marked with red background and dots.

<img width="321" alt="image" src="https://github.com/user-attachments/assets/c740fe3d-eed4-4f10-a405-deb79ccc2bf9">

**Comment by fvanroie** [comment]
In the editor field, press F1.
Then select Show Settings Menu `ctrl-,`
![image](https://github.com/user-attachments/assets/54a9858f-12e4-4576-80d6-ce938ac7e9d9)

Uncheck "Soft Tabs" and see if this fixes the tab problem.

**Comment by matsekberg** [comment]
Editor field?

**Comment by fvanroie** [comment]
The field where you type your jsonl code.

**Comment by matsekberg** [comment]
Ok found it and problem solved. Is it possible to make soft tabs disabled by default?
