### ISSUE TITLE
Sunton ESP32-8048S043C

### ISSUE THREAD

**Issue by RalfJL** [HASwitchPlate/openHASP#832]
### Perform all steps below and tick them with [x]
- [x] Check the related part of the [Documentation](https://www.openhasp.com/)
- [x] Update openHASP to the latest version
- [x] Reproduce the issue and describe all steps

### Describe the bug
Touchscreen dimension is wrong

### To Reproduce
Install latest Version of openHASP that supports this display and try to hit any button 

### Expected behavior
Button can be "touched"

### Screenshots or video
not possible

### Resolution 
change values in openHASP/user_setups/esp32S3
Section Sunton ESP32-8048S043C
to
   ; Touch Settings
    -D TOUCH_WIDTH=800
    -D TOUCH_HEIGHT=480

**Comment by fvanroie** [comment]
I believe there are 2 versions of this device: the old one with a low resolution captive touchscreen and a newer one with a high resolution touchscreen...

**Comment by RalfJL** [comment]
I would suggest to go with the newer one's because they are shipped now. I bought mine about a year ago.
But never mind, I can go with the sources.

**Comment by jonancy54** [comment]
me too , i have a white screen , but i can acces http page.

**Comment by RalfJL** [comment]
By the way. 
For the 8048S43C you can also use the binary of the 8048s50c 
It is simply the same but a little big bigger. And the touch resolution is correct with this binary.
